[tool.poetry]
name = "pacman"
version = "0.1.0"
description = ""
authors = ["Ivan Mincik <ivan.mincik@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
tcod = "^16.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
